name: CI Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Frontend (Vite + React) ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm test --if-present

      # --- Backend (.NET 8 / Orchard Core) ---
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore backend dependencies
        working-directory: backend
        run: dotnet restore

      - name: Build backend
        working-directory: backend
        run: dotnet build --configuration Release --no-restore

      - name: Run backend tests
        working-directory: backend
        run: dotnet test --no-build --verbosity normal
